# Generated by Django 2.2.3 on 2020-08-06 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0002_auto_20200717_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=-1, help_text='-1 denotes unlimited participants', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_slots',
            field=models.IntegerField(default=-1, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_slots_create_per_participant',
            field=models.IntegerField(default=-1, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_slots_join_per_participant',
            field=models.IntegerField(default=-1, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
