# Generated by Django 2.2.3 on 2020-08-14 13:53

import activity_calendar.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('activity_calendar', '0002_auto_20200814_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, help_text='If left empty, matches location with parent activity', max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='If left empty, matches start date with parent activity', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='If left empty, matches end date with parent activity', null=True)),
                ('recurrence_id', models.DateTimeField(blank=True, help_text='If the activity is recurring, set this to the date/time of one of its occurences. Leave this field empty if the parent activity is non-recurring.', null=True, verbose_name='parent activity date/time')),
                ('max_participants', models.IntegerField(default=-1, help_text='-1 denotes unlimited participants', validators=[django.core.validators.MinValueValidator(-1)])),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='subscriptions_close',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='activity',
            name='subscriptions_open',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='activity',
            name='subscriptions_required',
            field=models.BooleanField(default=True, help_text='People are only allowed to go to the event if they subscribe beforehand'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=activity_calendar.models.later_rounded),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_slots_create_per_participant',
            field=models.IntegerField(default=0, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_slots_join_per_participant',
            field=models.IntegerField(default=1, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='published_date',
            field=models.DateTimeField(default=activity_calendar.models.now_rounded),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=activity_calendar.models.now_rounded),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showed_up', models.BooleanField(default=None, help_text='Whether the participant actually showed up', null=True)),
                ('activity_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_calendar.ActivitySlot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExtendedUser')),
            ],
        ),
        migrations.AddField(
            model_name='activityslot',
            name='parent_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_activity', to='activity_calendar.Activity'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant_info', through='activity_calendar.Participant', to='core.ExtendedUser'),
        ),
    ]
