# Generated by Django 2.2.3 on 2020-10-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0003_auto_20200921_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': [('can_view_activity_participants_before', "Can view an activity's participants before it ends."), ('can_view_activity_participants_after', "Can view an activity's participants after it has ended."), ('can_register_outside_registration_period', 'Can (de)register for activities even if registrations are closed.'), ('can_manage_slots_outside_registration_period', 'Can create/modify/delete slots for activities even if registrations are closed.')], 'verbose_name_plural': 'activities'},
        ),
    ]
