# Generated by Django 2.2.15 on 2020-10-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0004_activitymoment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitymoment',
            old_name='last_updated_date',
            new_name='last_updated',
        ),
    ]
