# Generated by Django 2.2.3 on 2020-10-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0004_auto_20201014_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': [('can_view_activity_participants_before', "Can view an activity's participants before it ends."), ('can_view_activity_participants_after', "Can view an activity's participants after it has ended."), ('can_register_inside_registration_period', 'Can (de)register for activities if registrations are open.'), ('can_register_outside_registration_period', 'Can (de)register for activities if registrations are closed.'), ('can_manage_slots_inside_registration_period', 'Can create/modify/delete slots for activities if registrations are open.'), ('can_manage_slots_outside_registration_period', 'Can create/modify/delete slots for activities if registrations are closed.')], 'verbose_name_plural': 'activities'},
        ),
    ]
