# Generated by Django 2.2.3 on 2020-08-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0004_auto_20200806_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
    ]
