# Generated by Django 2.2.15 on 2020-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0004_activitymoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymoment',
            name='local_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
