# Generated by Django 2.2.3 on 2020-08-22 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presetimage'),
        ('activity_calendar', '0004_auto_20200819_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='auto_create_first_slot',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_slots_create_per_participant',
        ),
        migrations.AddField(
            model_name='activity',
            name='slot_creation',
            field=models.CharField(choices=[('CREATION_NONE', 'Never/By Administrators'), ('CREATION_AUTO', 'Automatically'), ('CREATION_USER', 'By Users')], default='CREATION_AUTO', max_length=15),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_slots',
            field=models.IntegerField(default=1, help_text='-1 denotes unlimited slots', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
