# Generated by Django 2.2.24 on 2021-08-09 11:44

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0007_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=core.fields.MarkdownTextField(),
        ),
        migrations.AlterField(
            model_name='activitymoment',
            name='local_description',
            field=core.fields.MarkdownTextField(blank=True, default=None, null=True),
        ),
    ]
