# Generated by Django 2.2.24 on 2021-08-10 14:38

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0007_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=core.fields.MarkdownTextField(help_text='Note that uploaded images are publicly accessible, even if the activity is unpublished.'),
        ),
        migrations.AlterField(
            model_name='activitymoment',
            name='local_description',
            field=core.fields.MarkdownTextField(blank=True, default=None, help_text='Note that uploaded images are publicly accessible, even if the activity is unpublished.', null=True),
        ),
    ]
