# Generated by Django 2.2.24 on 2021-09-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '009_alt_activitymoment_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitymoment',
            old_name='end_date',
            new_name='local_end_date',
        ),
        migrations.RenameField(
            model_name='activitymoment',
            old_name='start_date',
            new_name='local_start_date',
        ),
    ]
