# Generated by Django 2.2.15 on 2021-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0010_auto_20210905_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='promotion_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/activity/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='activitymoment',
            name='local_promotion_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/activity/%Y/%m/'),
        ),
    ]
