# Generated by Django 2.2.15 on 2021-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0012_participant_external_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityslot',
            name='participants',
        ),
        migrations.AlterField(
            model_name='participant',
            name='guest_name',
            field=models.CharField(default='', max_length=123),
        ),
    ]
