# Generated by Django 2.2.24 on 2021-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0012_participant_external_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='subscriptions_required',
            field=models.BooleanField(default=False, help_text='People are only allowed to go to the activity if they register beforehand'),
        ),
    ]
