# Generated by Django 2.2.15 on 2021-11-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0014_delete_extendeduser_references'),
        ('activity_calendar', '0014_auto_20211122_1706'),
    ]

    operations = [
    ]
