# Generated by Django 2.2.15 on 2021-11-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_longer_group_member_titles'),
        ('activity_calendar', '0014_delete_extendeduser_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_calendar.Activity')),
                ('association_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.AssociationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='organisers',
            field=models.ManyToManyField(through='activity_calendar.OrganiserLink', to='committees.AssociationGroup'),
        ),
    ]
