# Generated by Django 2.2.15 on 2021-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0015_organisers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymoment',
            name='status',
            field=models.CharField(choices=[('GO', 'Normal proceeed'), ('STOP', 'Cancel, with notification'), ('RMV', 'Remove')], default='GO', max_length=5),
        ),
    ]
