# Generated by Django 2.2.24 on 2021-12-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0016_activitymoment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreActivityGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='core_grouping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_calendar.CoreActivityGrouping'),
        ),
    ]
