# Generated by Django 2.2.15 on 2022-03-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0017_core_activity_groupings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(help_text='The local url string', verbose_name='url string')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If activity should be on public calendar'),
        ),
        migrations.CreateModel(
            name='CalendarActivityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_calendar.Activity')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_calendar.Calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='activities',
            field=models.ManyToManyField(through='activity_calendar.CalendarActivityLink', to='activity_calendar.Activity'),
        ),
    ]
