# Generated by Django 2.2.27 on 2022-04-09 14:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0018_activityslot_link_to_activitymoment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityslot',
            name='parent_activity',
        ),
        migrations.RemoveField(
            model_name='activityslot',
            name='recurrence_id',
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='parent_activitymoment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_slot_set', to='activity_calendar.ActivityMoment')
        ),
    ]
