# Generated by Django 2.2.15 on 2022-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0018_auto_20220312_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(help_text='The local url string', unique=True, verbose_name='url string'),
        ),
    ]
