# Generated by Django 2.2.15 on 2022-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0019_auto_20220312_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='full_day',
            field=models.BooleanField(default=False, help_text='Whether this event marks the entire day'),
        ),
        migrations.AddField(
            model_name='activitymoment',
            name='local_full_day',
            field=models.BooleanField(blank=True, default=None, help_text='Whether this event marks the entire day', null=True),
        ),
    ]
