# Generated by Django 2.2.15 on 2022-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0018_auto_20220411_1555'),
        ('activity_calendar', '0020_auto_20220320_2314'),
    ]

    operations = [
    ]
