# Generated by Django 2.2.15 on 2022-03-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0016_auto_20211231_1334'),
        ('activity_calendar', '0020_auto_20220313_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCalendarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('use_birthday', models.BooleanField(default=False, verbose_name='Display my birthday in Knights birthday calendar')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership_file.Member')),
            ],
        ),
    ]
