# Generated by Django 2.2.15 on 2022-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0021_merge_20220416_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='display_end_time',
            field=models.BooleanField(default=False, help_text='Whether the end time is displayed on the site'),
        ),
    ]
