# Generated by Django 3.2.16 on 2023-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0023_activityslot_link_to_activitymoment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': [('can_view_activity_participants_before', "[F] Can view an activity's participants before it starts."), ('can_view_activity_participants_during', "[F] Can view an activity's participants during it."), ('can_view_activity_participants_after', "[F] Can view an activity's participants after it has ended."), ('can_register_outside_registration_period', '[F] Can (de)register for activities if registrations are closed.'), ('can_ignore_none_slot_creation_type', '[F] Can create slots for activities with slots that normally do not allow slot creation by users.'), ('can_ignore_slot_creation_limits', '[F] Can create more slots even if the maximum amount of slots is reached.'), ('can_select_slot_image', '[F] Can choose an alternative slot image when creating a slot.'), ('can_view_private_slot_locations', "[F] Can view a slot's location even if they are marked as 'private' by the activity."), ('can_host_meetings', '[F] Can host meetings')], 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public activity'), ('MEETING', 'Meeting')], default='PUBLIC', max_length=8),
        ),
    ]
