# Generated by Django 3.2.16 on 2023-03-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0027_alter_activity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_public',
        ),
    ]
