# Generated by Django 2.2.24 on 2021-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_calendar', '0008_markdown_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymoment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitymoment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
