# Generated by Django 2.2.3 on 2020-02-26 12:04

import achievements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=255)),
                ('category', models.ForeignKey(on_delete=models.SET(achievements.models.get_or_create_default_category), related_name='related_achievements', to='achievements.Category')),
                ('claimants', models.ManyToManyField(blank=True, related_name='claimed_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_claimants', 'Can view the claimants of Achievements')],
            },
        ),
    ]
