# Generated by Django 2.2.3 on 2020-03-31 12:40

import achievements.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to=achievements.models.get_achievement_image_upload_path)),
                ('unlocked_text', models.CharField(default='Claimed by {0} on {1}.', help_text='{0}: User Display Name, {1}: Date Unlocked, {2}: Extra Data 1 (int), {3}: Extra Data 2 (string), {4}: Extra Data 3 (string)', max_length=127)),
                ('claimants_sort_field', models.CharField(choices=[('date_unlocked', 'Unlocked Date'), ('extra_data_1', 'Extra Data 1'), ('extra_data_2', 'Extra Data 2'), ('extra_data_3', 'Extra Data 3')], default='date_unlocked', max_length=31)),
                ('claimants_sort_ascending', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'permissions': [('can_view_claimants', 'Can view the claimants of Achievements')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlocked', models.DateField(default=django.utils.timezone.now)),
                ('extra_data_1', models.IntegerField(blank=True, null=True)),
                ('extra_data_2', models.CharField(blank=True, max_length=63, null=True)),
                ('extra_data_3', models.CharField(blank=True, max_length=63, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Achievement')),
            ],
        ),
    ]
