# Generated by Django 2.2.3 on 2019-09-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('achievements', '0001_initial'), ('achievements', '0002_auto_20190826_2224'), ('achievements', '0003_auto_20190826_2225'), ('achievements', '0004_auto_20190827_1317'), ('achievements', '0005_auto_20190827_1317'), ('achievements', '0006_auto_20190827_1330'), ('achievements', '0007_auto_20190827_1332'), ('achievements', '0008_auto_20190827_1402'), ('achievements', '0009_auto_20190827_1414'), ('achievements', '0010_auto_20190827_1416'), ('achievements', '0011_auto_20190828_1033')]

    initial = True

    dependencies = [
        ('membership_file', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=255)),
                ('category', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_achievements', to='achievements.Category')),
                ('claimants', models.ManyToManyField(blank=True, related_name='claimed_achievements', to='membership_file.Member')),
            ],
        ),
    ]
