# Generated by Django 2.2.3 on 2020-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
