# Generated by Django 2.2.3 on 2019-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='claimants',
            field=models.ManyToManyField(to='achievements.Test'),
        ),
    ]
