# Generated by Django 2.2.3 on 2020-03-31 12:40

import achievements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExtendedUser'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(achievements.models.get_or_create_default_category), related_name='related_achievements', to='achievements.Category'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='claimants',
            field=models.ManyToManyField(blank=True, related_name='claimant_info', through='achievements.Claimant', to='core.ExtendedUser'),
        ),
    ]
