# Generated by Django 2.2.3 on 2020-10-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20200331_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name', 'id'], 'permissions': [('can_view_claimants', '[F] Can view the claimants of Achievements.')]},
        ),
    ]
