# Generated by Django 2.2.3 on 2019-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20190826_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='claimants',
            field=models.ManyToManyField(to='membership_file.Member'),
        ),
    ]
