# Generated by Django 2.2.8 on 2021-07-25 00:22

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('achievements', '0003_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Achievement')),
                ('content_type', models.ForeignKey(limit_choices_to=inventory.models.valid_item_class_ids, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
