# Generated by Django 2.2.24 on 2021-11-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_auto_20210809_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='claimants',
            field=models.ManyToManyField(blank=True, related_name='claimant_info', through='achievements.Claimant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
