# Generated by Django 2.2.3 on 2019-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_auto_20190827_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='claimants',
            field=models.ManyToManyField(blank=True, related_name='related_achievements', to='membership_file.Member'),
        ),
    ]
