# Generated by Django 2.2.3 on 2020-08-19 14:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('selectable', models.BooleanField(default=True)),
            ],
        ),
    ]
