# Generated by Django 2.2.3 on 2020-10-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0002_presetimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('group_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='group_info', serialize=False, to='auth.Group')),
                ('description', models.TextField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('can_be_deleted', models.BooleanField(default=True, help_text="Groups that cannot be deleted are used in Squire's source code.")),
            ],
            bases=('auth.group',),
        ),
    ]
