# Generated by Django 2.2.3 on 2020-10-21 15:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0002_presetimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('group_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='group_info', serialize=False, to='auth.Group')),
                ('description', models.TextField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
            ],
            bases=('auth.group',),
            managers=[
                ('public_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
