# Generated by Django 2.2.3 on 2020-10-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presetimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presetimage',
            options={'permissions': [('can_select_presetimage_any', '[F] Can choose PresetImages that are normally not selectable.')]},
        ),
    ]
