# Generated by Django 2.2.17 on 2021-07-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presetimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presetimage',
            options={'permissions': [('can_select_presetimage_any', '[F] Can choose PresetImages that are normally not selectable.')]},
        ),
    ]
