# Generated by Django 2.2.3 on 2020-10-21 18:35

from django.db import migrations

from core.util import make_default_groups


default_groups = (
    # The default group that is given to everyone that creates an account.
    {
        'name': "Account Owner",
        'description': "Default group granted to everyone who creates an account.",
        'is_public': False,
    },
)


def handle_default_user_group(apps, schema_editor):
    """
    Creates the default 'Account Owner' group that is granted to everyone who creates
    an account. Also assigns all existing users to this group.
    """
    make_default_groups(apps, default_groups)

    user_group = apps.get_model('core', 'ExtendedGroup').objects.get(name='Account Owner')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        user.groups.add(user_group)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extendedgroup'),
    ]

    operations = [
        migrations.RunPython(handle_default_user_group),
    ]
