# Generated by Django 2.2.3 on 2020-10-21 18:35

from django.db import migrations


default_groups = (
    # The default group that is given to everyone that creates an account.
    {
        'name': "Users",
        'description': "Default group granted to everyone who creates an account.",
        'is_public': False,
    },
)

def make_default_groups(apps, schema_editor):
    """
    Creates several groups that are used throughout the application
    """
    Group = apps.get_model('core', 'ExtendedGroup')
    for group in default_groups:
        Group.objects.get_or_create(**group)

def give_users_default_group(apps, schema_editor):
    """
    Assigns each existing user who is also a member to the "Member" Group
    """
    user_group = apps.get_model('core', 'ExtendedGroup').objects.get(name='Users')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        user.groups.add(user_group)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extendedgroup'),
    ]

    operations = [
        migrations.RunPython(make_default_groups),
        migrations.RunPython(give_users_default_group),
    ]
