# Generated by Django 2.2.3 on 2020-10-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_DATA_default_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='extendedgroup',
            managers=[
            ],
        ),
    ]
