# Generated by Django 2.2.24 on 2021-11-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_markdownimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
