# Generated by Django 2.2.24 on 2021-11-26 11:47

import core.pin_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=127)),
                ('pin_date', models.DateTimeField(default=core.pin_models.now_rounded, help_text='Pins are sorted based on this value.')),
                ('local_title', models.CharField(blank=True, max_length=255)),
                ('local_description', models.TextField(blank=True)),
                ('local_url', models.URLField(blank=True)),
                ('local_publish_date', models.DateTimeField(blank=True, default=core.pin_models.now_rounded, help_text='The date at which this pin becomes available. Can be left empty to never become available.', null=True)),
                ('local_expiry_date', models.DateTimeField(blank=True, default=core.pin_models.now_one_week_later, help_text='The date at which this pin is no longer available. Can be left empty to not expire.', null=True)),
                ('is_members_only', models.BooleanField(default=True, help_text="'Members-only' pins can only be viewed by those with the permission to do so.")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=core.pin_models.valid_pinnable_models, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('local_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PresetImage')),
            ],
            options={
                'ordering': ['-pin_date'],
                'permissions': [('can_view_members_only_pins', "[F] Can view pins that are marked as 'members only'."), ('can_view_expired_pins', '[F] Can view pins that have expired.'), ('can_view_future_pins', '[F] Can view pins with a publish date in the future.')],
            },
        ),
    ]
