# Generated by Django 2.2.25 on 2021-12-30 18:07

import core.pin_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'permissions': [('can_view_members_only_pins', "[F] Can view pins that are marked as 'members only'."), ('can_view_expired_pins', '[F] Can view pins that have expired.'), ('can_view_future_pins', '[F] Can view pins with a publish date in the future.')]},
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin_date',
            new_name='local_pin_date',
        ),
        migrations.AddField(
            model_name='pin',
            name='highlight_duration',
            field=models.DurationField(blank=True, help_text='How long this pin will be highlighted on the homepage. It will still be accessible until it expires. Leave empty to highlight it until it expires.', null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='local_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='local_expiry_date',
            field=models.DateTimeField(blank=True, default=core.pin_models.now_one_year_later, help_text='The date at which this pin is no longer available. Can be left empty to not expire.', null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='local_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='local_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
