# Generated by Django 2.2.25 on 2022-02-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='description',
            field=models.CharField(blank=True, help_text='Will be displayed when sharing the link on e.g. Telegram or Whatsapp', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='location',
            field=models.CharField(help_text='The local url e.g. intro results in <squire-domain>.nl/intro', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='reference_url',
            field=models.URLField(help_text="The url it references to. It should be the full url e.g. 'https://www.google.com'"),
        ),
    ]
