# Generated by Django 2.2.25 on 2021-12-31 10:41

import core.pin_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211230_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='local_pin_date',
            field=models.DateTimeField(blank=True, default=core.pin_models.now_rounded, help_text='Pins are sorted based on this value.', null=True),
        ),
    ]
