# Generated by Django 4.2.16 on 2024-11-02 13:20

import discord_integration.models
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedOAuthToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expiry_date", models.DateTimeField()),
                ("name", models.CharField(max_length=256)),
                (
                    "metadata",
                    models.JSONField(
                        default=discord_integration.models.LinkedOAuthToken.metadata_default,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="linkedoauthtoken",
            constraint=models.UniqueConstraint(fields=("name", "user"), name="unique user for web service"),
        ),
    ]
