# Generated by Django 2.2.3 on 2019-07-06 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('tussenvoegsel', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=64)),
                ('tue_card_number', models.CharField(blank=True, max_length=8)),
                ('external_card_number', models.CharField(blank=True, max_length=16)),
                ('date_of_birth', models.DateField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+\\d{8,15}$')])),
                ('member_since', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
