# Generated by Django 2.2.3 on 2020-02-14 20:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('tue_card_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 numbers. E.g. 1234567', regex='^[0-9]{7}$')], verbose_name='TUe card number')),
                ('external_card_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 numbers. E.g. 1234567', regex='^[0-9]{7}$')])),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+[0-9]{8,15}$')])),
                ('member_since', models.DateField(default=datetime.date.today)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_user', to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=255)),
                ('house_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('house_number_addition', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('external_card_cluster', models.CharField(blank=True, max_length=255, null=True, verbose_name='cluster')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state/province')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('educational_institution', models.CharField(max_length=255)),
                ('student_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('external_card_digits', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='External card digits must consist of exactly 3 digits. E.g. 012', regex='^[0-9]{3}$')], verbose_name='digits')),
                ('initials', models.CharField(help_text='Initials as known by your Educational Institution.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Initials must be capital letters only, and must be separated by dots. E.g. A.B.', regex='^([A-Z]\\.)+$')])),
            ],
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_member', to='membership_file.Member')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_that_updated', to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemberLogField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('member_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_in_member_log', to='membership_file.MemberLog')),
            ],
        ),
    ]
