# Generated by Django 2.2.3 on 2019-07-10 12:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=63)),
                ('tue_card_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Card numbers must only consist of numbers.', regex='^[0-9]*$')])),
                ('external_card_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Card numbers must only consist of numbers.', regex='^[0-9]*$')])),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+[0-9]{8,15}$')])),
                ('member_since', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_user', to=settings.AUTH_USER_MODEL)),
                ('city_of_residence', models.CharField(max_length=63)),
                ('house_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('house_number_addition', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code (Dutch variant) must be entered in the format: '1234 AB'.", regex='^[0-9]{4} [A-Z]{2}$')])),
                ('street', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=63)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_member', to='membership_file.Member')),
                ('new_value', models.CharField(max_length=63)),
                ('old_value', models.CharField(max_length=63)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_that_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
