# Generated by Django 2.2.3 on 2020-03-30 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='This email address is used by the board to contact you.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_card_number',
            field=models.CharField(blank=True, help_text='External cards are blue, whereas Tu/e cards are (currently) orange.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 numbers. E.g. 1234567', regex='^[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, help_text='A phone number is required if you want access to our rooms.', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+31651018209'. Up to 14 digits allowed.", regex='^\\+[0-9]{8,15}$')]),
        ),
    ]
