# Generated by Django 2.2.3 on 2020-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deregistered',
            field=models.BooleanField(default=False, help_text='Use this if you need to store (contact) information of someone who is not a member anymore.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='house_number_addition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='addition'),
        ),
    ]
