# Generated by Django 2.2.3 on 2020-10-14 17:03

from django.db import migrations

default_groups = (
    # The default group that is given to all users in the membership file.
    {'name': 'Member', 'description': 'Users that have verified themselves to be members.', 'is_public': True},
    # Special group that can be assigned special permissions manually
    {'name': 'Board Member', 'description': 'Users that have more rights within Squire.', 'is_public': True},
)

def make_default_groups(apps, schema_editor):
    """
    Creates several groups that are used throughout the application
    """
    Group = apps.get_model('core', 'ExtendedGroup')
    for group in default_groups:
        Group.objects.get_or_create(**group)

def give_members_member_groups(apps, schema_editor):
    """
    Assigns each existing user who is also a member to the "Member" Group
    """
    member_group = apps.get_model('core', 'ExtendedGroup').objects.filter(name='Member').first()
    Member = apps.get_model('membership_file', 'Member')

    for member in Member.objects.filter(user__isnull=False):
        member.user.groups.add(member_group)

class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0002_auto_20200914_1644'),
        ('core', '0003_extendedgroup'),
    ]

    operations = [
        migrations.RunPython(make_default_groups),
        migrations.RunPython(give_members_member_groups),
    ]
