# Generated by Django 2.2.3 on 2020-02-06 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0002_auto_20190914_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='external_card_digits',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='External card digits must consist of exactly 3 digits. E.g. 012', regex='^[0-9]{3}$')], verbose_name='digits'),
        ),
        migrations.AddField(
            model_name='member',
            name='initials',
            field=models.CharField(help_text='Initials as known by your Educational Institution.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Initials must be capital letters only, and must be separated by dots. E.g. A.B.', regex='^([A-Z]\\.)+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_card_cluster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cluster'),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 numbers. E.g. 1234567', regex='^[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='state/province'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tue_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 numbers. E.g. 1234567', regex='^[0-9]{7}$')], verbose_name='TUe card number'),
        ),
    ]
