# Generated by Django 2.2.3 on 2019-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0002_auto_20190706_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tussenvoegsel',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
