# Generated by Django 2.2.3 on 2020-10-23 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0002_auto_20200914_1644')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_view_membership_information_self', 'Can view their own membership information.'), ('can_change_membership_information_self', 'Can edit their own membership information.')]},
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
