# Generated by Django 2.2.3 on 2020-10-14 17:03

from django.db import migrations

from core.util import make_default_groups

default_groups = (
    # The default group that is given to all users in the membership file.
    {
        'name': 'Member',
        'description': 'Users that have verified themselves to be members.',
        'is_public': True,
        'can_be_deleted': False
    },
    # Special group that can manage Squire's membership file.
    {
        'name': 'Board Member',
        'description': 'Users that can manage Squire''s membership file and see its history.',
        'is_public': True,
        'can_be_deleted': False
    },
)


def handle_default_membership_file_groups(apps, schema_editor):
    """
    Creates the 'Member' and 'Board Member' groups, and assigns each existing user
    who is also a member to the "Member" Group.
    """
    make_default_groups(apps, default_groups)

    member_group = apps.get_model('core', 'ExtendedGroup').objects.filter(name='Member').first()
    Member = apps.get_model('membership_file', 'Member')

    for member in Member.objects.filter(user__isnull=False):
        member.user.groups.add(member_group)

class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0003_auto_20201023_1037'),
        ('core', '0003_extendedgroup'),
    ]

    operations = [
        migrations.RunPython(handle_default_membership_file_groups),
    ]
