# Generated by Django 2.2.24 on 2021-08-09 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0007_auto_20210802_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='external_card_number',
            field=models.CharField(blank=True, help_text='External cards are blue, whereas Tu/e cards are (currently) orange.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 or 8 digits. E.g. 1234567', regex='^[0-9]{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tue_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 7 or 8 digits. E.g. 1234567', regex='^[0-9]{7,8}$')], verbose_name='TUe card number'),
        ),
    ]
