# Generated by Django 2.2.24 on 2021-08-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0008_tue_card_number_length_8'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_view_membership_information_self', '[F] Can view their own membership information.'), ('can_change_membership_information_self', '[F] Can edit their own membership information.')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['access', 'name']},
        ),
    ]
