# Generated by Django 2.2.24 on 2021-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0009_model_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_view_membership_information_self', '[F] Can view their own membership information.'), ('can_change_membership_information_self', '[F] Can edit their own membership information.'), ('can_export_membership_file', 'Can export the membership file.')]},
        ),
    ]
