# Generated by Django 2.2.15 on 2021-09-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0010_export_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberUser',
        ),
    ]
