# Generated by Django 2.2.15 on 2021-12-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0013_red_tue_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to='membership_file.Member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_file.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(through='membership_file.Membership', to='membership_file.Member')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_file.MemberYear'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'year')},
        ),
    ]
