# Generated by Django 2.2.15 on 2021-12-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0014_auto_20211220_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'year')},
        ),
    ]
