# Generated by Django 2.2.15 on 2021-12-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0014_memberyears_aditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberyear',
            options={'ordering': ('-name',)},
        ),
    ]
