# Generated by Django 2.2.15 on 2021-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0015_auto_20211220_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
