# Generated by Django 2.2.15 on 2022-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0016_auto_20211231_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_birthday_in_calendar',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
