# Generated by Django 2.2.15 on 2021-12-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0016_memberyear_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to='membership_file.Member'),
        ),
    ]
