# Generated by Django 3.2.16 on 2023-01-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0016_auto_20211231_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='has_paid_membership_fee',
        ),
    ]
