# Generated by Django 2.2.15 on 2021-12-20 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0017_membership_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
