# Generated by Django 3.2.25 on 2024-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_file", "0018_membership_member_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="access",
            new_name="access_specification",
        ),
        migrations.AddField(
            model_name="room",
            name="access_type",
            field=models.CharField(
                choices=[("KEY", "Key"), ("CARD", "TUe Card/External Card"), ("MISC", "Other")],
                default="MISC",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="room_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="room",
            name="access_specification",
            field=models.CharField(blank=True, help_text="E.g. key number", max_length=15),
        ),
    ]
