# Generated by Django 3.2.25 on 2024-09-07 16:47

from django.db import migrations


def extend_card_numbers(apps, schema_editor):
    """Extends the tue/external card numbers to 8 digits, and the external card digits to 4 digits"""
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Member = apps.get_model("membership_file", "Member")
    for member in Member.objects.all():
        if member.external_card_digits:
            member.external_card_digits = member.external_card_digits.zfill(4)
            member.last_updated_by = None
        if member.external_card_number:
            member.external_card_number = member.external_card_number.zfill(8)
            member.last_updated_by = None
        if member.tue_card_number:
            member.tue_card_number = member.tue_card_number.zfill(8)
            member.last_updated_by = None
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("membership_file", "0019_room_cards"),
    ]

    operations = [
        migrations.RunPython(extend_card_numbers),
    ]
