# Generated by Django 3.2.25 on 2024-09-07 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0020_card_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='external_card_cluster',
        ),
        migrations.AlterField(
            model_name='member',
            name='external_card_digits',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='External card digits must consist of exactly 4 digits. E.g. 0012', regex='^[0-9]{4}$')], verbose_name='digits'),
        ),
        migrations.AlterField(
            model_name='member',
            name='external_card_number',
            field=models.CharField(blank=True, help_text="External cards mention 'FMC', whereas Tu/e cards are currently red (since sept. 2021) or orange (before sept. 2021).", max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 8 digits. For older cards (pre 2017) that only used 7 digits, prepend a 0. E.g. 01457347', regex='^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='tue_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TUe card numbers must only consist of exactly 8 digits. For older cards (pre 2017) that only used 7 digits, prepend a 0. E.g. 01457347', regex='^[0-9]{8}$')], verbose_name='TUe card number'),
        ),
    ]
