# Generated by Django 5.2.15 on 2026-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_file", "0021_card_lengths_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberyear",
            name="members",
            field=models.ManyToManyField(
                through="membership_file.Membership", through_fields=["year", "member"], to="membership_file.member"
            ),
        ),
    ]
