# Generated by Django 2.2.15 on 2021-08-12 16:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('shorthand', models.CharField(max_length=16)),
                ('icon', models.ImageField(upload_to='images/committees/')),
                ('type', models.CharField(choices=[('C', 'Committee'), ('O', 'Order'), ('WG', 'Workgroup'), ('B', 'Board')], max_length=2)),
                ('is_public', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.TextField()),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
