# Generated by Django 2.2.15 on 2021-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=16)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/committees/')),
                ('type', models.CharField(choices=[('C', 'Committee'), ('O', 'Order'), ('WG', 'Workgroup'), ('B', 'Board')], max_length=2)),
                ('is_public', models.BooleanField(default=False)),
                ('short_description', models.CharField(blank=True, max_length=128, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('site_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
