# Generated by Django 2.2.15 on 2021-08-27 11:40

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_file', '0008_tue_card_number_length_8'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(blank=True, max_length=16, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/committees/')),
                ('type', models.CharField(choices=[('C', 'Committee'), ('O', 'Guild'), ('WG', 'Workgroup'), ('B', 'Board')], max_length=2)),
                ('is_public', models.BooleanField(default=True)),
                ('short_description', models.CharField(blank=True, max_length=128, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('site_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('instructions', core.fields.MarkdownTextField(blank=True, help_text='Information displayed on internal info page', max_length=2047, null=True)),
            ],
            options={
                'ordering': ('shorthand',),
            },
        ),
        migrations.CreateModel(
            name='GroupExternalUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('association_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcut_set', to='committees.AssociationGroup')),
                ('description', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', help_text='Name of the formal role. E.g. treasurer, president', max_length=32)),
                ('title', models.CharField(blank=True, default='', help_text="Symbolic name (if any) e.g. 'God of War', 'Minister of Alien affairs', or 'Wondrous Wizard'", max_length=32)),
                ('joined_since', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.AssociationGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_file.Member')),
            ],
            options={
                'unique_together': {('member', 'group')},
                'ordering': ['-role', 'member__legal_name'],
            },
        ),
        migrations.AddField(
            model_name='associationgroup',
            name='members',
            field=models.ManyToManyField(through='committees.AssociationGroupMembership', to='membership_file.Member'),
        ),
        migrations.AddField(
            model_name='associationgroup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
