# Generated by Django 2.2.15 on 2021-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationgroup',
            options={'ordering': ('shorthand',)},
        ),
        migrations.AlterField(
            model_name='associationgroup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='associationgroup',
            name='shorthand',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='associationgroup',
            name='type',
            field=models.CharField(choices=[('C', 'Committee'), ('O', 'Guild'), ('WG', 'Workgroup'), ('B', 'Board')], max_length=2),
        ),
    ]
