# Generated by Django 2.2.15 on 2021-08-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationgroup',
            options={'ordering': ('shorthand',), 'permissions': [('can_view_committee_members', 'Can view committee members'), ('can_view_order_members', 'Can view order members'), ('can_view_board_members', 'Can view board members')]},
        ),
    ]
