# Generated by Django 2.2.15 on 2021-08-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_auto_20210821_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationgroup',
            name='instructions',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
        migrations.CreateModel(
            name='GroupExternalUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('association_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcut_set', to='committees.AssociationGroup')),
            ],
        ),
    ]
