# Generated by Django 2.2.15 on 2021-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20210822_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexternalurls',
            name='description',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
