# Generated by Django 2.2.15 on 2021-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20210903_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationgroup',
            name='type',
            field=models.CharField(choices=[('C', 'Committee'), ('O', 'Order'), ('WG', 'Workgroup'), ('B', 'Board')], max_length=2),
        ),
    ]
