# Generated by Django 2.2.15 on 2021-08-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_groupexternalurls_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupExternalUrls',
            new_name='GroupExternalUrl',
        ),
    ]
