# Generated by Django 3.2.16 on 2023-01-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_add_and_fill_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroupPanelControl',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committees.associationgroup',),
        ),
    ]
