# Generated by Django 2.2.15 on 2022-04-17 12:43

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    AssociationGroup = apps.get_model("committees", "AssociationGroup")
    db_alias = schema_editor.connection.alias
    for association_group in AssociationGroup.objects.using(db_alias).all():
        association_group.name = association_group.site_group.name
        association_group.save()

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    AssociationGroup = apps.get_model("committees", "AssociationGroup")
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    for association_group in AssociationGroup.objects.using(db_alias).all():
        if association_group.site_group is None:
            group = Group.objects.alias(db_alias).create(
                name = association_group.name,
            )
            association_group.site_group = group
            association_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_associationgrouppanelcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationgroup',
            name='name',
            field=models.CharField(default='fake_name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associationgroup',
            name='site_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='associationgroup',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
