# Generated by Django 2.2.15 on 2021-08-23 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0008_tue_card_number_length_8'),
        ('committees', '0006_auto_20210823_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Name of the formal role. E.g. treasurer, president', max_length=32, null=True)),
                ('title', models.CharField(blank=True, help_text="Symbolic name (if any) e.g. 'God of War', 'Minister of Alien affairs', or 'Wondrous Wizard'", max_length=32, null=True)),
                ('joined_since', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.AssociationGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_file.Member')),
            ],
        ),
        migrations.AddField(
            model_name='associationgroup',
            name='members',
            field=models.ManyToManyField(through='committees.AssociationGroupMembership', to='membership_file.Member'),
        ),
    ]
