# Generated by Django 2.2.15 on 2022-04-17 14:33

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    AssociationGroup = apps.get_model("committees", "AssociationGroup")
    db_alias = schema_editor.connection.alias
    #  Move the entire list of permissions over to association group
    for association_group in AssociationGroup.objects.using(db_alias).all():
        if association_group.site_group is not None:
            association_group.permissions.set(association_group.site_group.permissions.all())
            association_group.site_group.permissions.clear()

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    AssociationGroup = apps.get_model("committees", "AssociationGroup")
    db_alias = schema_editor.connection.alias
    for association_group in AssociationGroup.objects.using(db_alias).all():
        # Transfer all permissions to the group object, keep any perms there in tact.
        if association_group.site_group:
            for perm in association_group.permissions.all():
                association_group.site_group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('committees', '0006_add_and_fill_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
