# Generated by Django 2.2.15 on 2022-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_associationgroup_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationgroup',
            name='type',
            field=models.CharField(choices=[('C', 'Committee'), ('O', 'Order'), ('WG', 'Workgroup'), ('B', 'Board'), ('GC', 'Campaign')], max_length=2),
        ),
    ]
