# Generated by Django 3.2.16 on 2023-01-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_associationgrouppanelcontrol'),
        ('committees', '0008_auto_20220417_2305'),
    ]

    operations = [
    ]
