# Generated by Django 2.2.15 on 2021-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_auto_20210824_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationgroupmembership',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Name of the formal role. E.g. treasurer, president', max_length=32),
        ),
        migrations.AlterField(
            model_name='associationgroupmembership',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Symbolic name (if any) e.g. 'God of War', 'Minister of Alien affairs', or 'Wondrous Wizard'", max_length=32),
        ),
    ]
