# Generated by Django 3.2.16 on 2023-05-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_file', '0018_membership_member_null'),
        ('committees', '0008_auto_20220417_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committees.associationgroup'),
        ),
        migrations.AlterField(
            model_name='associationgroupmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership_file.member'),
        ),
    ]
