# Generated by Django 2.2.15 on 2021-08-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0009_auto_20210824_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationgroupmembership',
            options={'ordering': ['-role', 'member__legal_name']},
        ),
    ]
