# Generated by Django 2.2.15 on 2021-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0010_auto_20210824_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationgroup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
