# Generated by Django 2.2.8 on 2021-08-03 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_ownership_is_active'), ('inventory', '0003_auto_20210724_1647'), ('inventory', '0004_auto_20210725_0113'), ('inventory', '0005_auto_20210725_1240'), ('inventory', '0006_ownership_note'), ('inventory', '0007_ownership_added_by'), ('inventory', '0008_auto_20210728_1505'), ('inventory', '0009_auto_20210728_2019'), ('inventory', '0010_auto_20210802_1513')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('membership_file', '0004_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_since', models.DateField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=inventory.models.valid_item_class_ids, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_file.Member')),
                ('is_active', models.BooleanField(default=True, help_text='Whether item is currently at the Knights')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('note', models.TextField(blank=True, max_length=256, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('bgg_id', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_item_image_upload_path)),
            ],
            options={
                'abstract': False,
                'ordering': ('name',),
                'default_permissions': ('add', 'change', 'delete', 'view', 'add_group_ownership_for', 'add_member_ownership_for', 'maintain_ownerships_for'),
            },
        ),
    ]
