# Generated by Django 2.2.15 on 2021-08-03 15:36

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_20210803_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_item_image_upload_path)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'add_group_ownership_for', 'add_member_ownership_for', 'maintain_ownerships_for'),
            },
        ),
    ]
