# Generated by Django 2.2.8 on 2021-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether item is currently at the Knights'),
        ),
    ]
