# Generated by Django 2.2.15 on 2021-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210803_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='play_duration',
            field=models.CharField(blank=True, choices=[('XS', '<15 min.'), ('S', '< 1 hour'), ('N', '1-2 hours'), ('L', '3-4 hours'), ('XL', '4+ hours')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='player_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='player_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
