# Generated by Django 2.2.15 on 2021-08-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210811_1539'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='BoardGame',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='BoardGame',
                    table='boardgames_boardgame',
                ),
            ],
        ),
    ]
