# Generated by Django 2.2.8 on 2021-07-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210724_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
