# Generated by Django 2.2.15 on 2021-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_move_boardgame_part_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
