# Generated by Django 2.2.8 on 2021-07-25 10:40

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210725_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_item_image_upload_path),
        ),
    ]
