# Generated by Django 2.2.8 on 2021-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210725_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='note',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
