# Generated by Django 2.2.15 on 2021-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ownership_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipValueProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Association inventory value',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.ownership',),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='initial purchase value'),
        ),
    ]
