# Generated by Django 2.2.8 on 2021-07-28 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ownership_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ('name',), 'permissions': [('can_add_boardgame_for_group', 'Can add boardgames item ownership for a group.'), ('can_add_boardgame_for_member', 'Can add boardgames item ownership for members.'), ('can_maintain_boardgame_ownerships', 'Can maintain boardgame ownerships.')]},
        ),
        migrations.AlterField(
            model_name='ownership',
            name='added_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
