# Generated by Django 2.2.15 on 2021-07-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210728_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgame',
            old_name='note',
            new_name='description',
        ),
    ]
