# Generated by Django 2.2.8 on 2021-08-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210728_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'add_group_ownership_for', 'add_member_ownership_for', 'maintain_ownerships_for'), 'ordering': ('name',)},
        ),
    ]
