# Generated by Django 2.2.15 on 2022-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_longer_group_member_titles'),
        ('surveys', '0002_auto_20220118_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='owners',
            field=models.ManyToManyField(to='committees.AssociationGroup'),
        ),
    ]
