# Generated by Django 2.2.15 on 2022-01-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='owners',
            new_name='organiser',
        ),
    ]
