# Generated by Django 2.2.15 on 2022-01-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20220119_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='organiser',
            new_name='organisers',
        ),
    ]
