# Generated by Django 2.2.15 on 2022-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20220119_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='organisers',
            field=models.ManyToManyField(blank=True, null=True, to='committees.AssociationGroup'),
        ),
    ]
