# Generated by Django 2.2.15 on 2022-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20220119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='organisers',
            field=models.ManyToManyField(blank=True, to='committees.AssociationGroup'),
        ),
    ]
