# Generated by Django 2.2.8 on 2021-08-13 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import roleplaying.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleplayingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this system should be displayed on the roleplaying systems page', verbose_name='On Systems page')),
                ('image', models.ImageField(blank=True, null=True, upload_to=roleplaying.models.get_system_image_upload_path)),
                ('player_count', models.CharField(blank=True, max_length=8, null=True)),
                ('rate_complexity', models.IntegerField(blank=True, choices=[(1, 'No rules'), (2, 'Rules-light'), (3, 'Average'), (4, 'Rule-heavy'), (5, 'Robust')], null=True)),
                ('rate_lore', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dice', models.TextField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleplayingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_item_image_upload_path)),
                ('local_file', models.FileField(blank=True, null=True, upload_to=roleplaying.models.get_roleplay_item_file_upload_path)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='roleplaying.RoleplayingSystem')),
                ('local_file_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Filename (without extension)')),
                ('external_file_url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'add_group_ownership_for', 'add_member_ownership_for', 'maintain_ownerships_for'),
            },
        ),
    ]
