# Generated by Django 2.2.8 on 2021-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0001_squashed_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleplayingsystem',
            old_name='is_live',
            new_name="is_public",
        ),
        migrations.AlterField(
            model_name='roleplayingsystem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this system should be displayed on the roleplaying systems page', verbose_name='On Systems page'),
        ),
    ]
