# Generated by Django 2.2.15 on 2021-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingsystem',
            name='dice',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
