# Generated by Django 2.2.15 on 2021-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0002_auto_20210822_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayingsystem',
            name='more_info_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
