# Generated by Django 2.2.8 on 2021-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0002_auto_20210803_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayingitem',
            name='digital_version_file_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
