# Generated by Django 2.2.15 on 2021-08-22 15:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0003_roleplayingsystem_more_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingsystem',
            name='long_description',
            field=core.fields.MarkdownTextField(blank=True, null=True),
        ),
    ]
