# Generated by Django 2.2.8 on 2021-08-02 23:17

from django.db import migrations, models
import roleplaying.models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0003_roleplayingitem_digital_version_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayingsystem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=roleplaying.models.get_system_image_upload_path),
        ),
    ]
