# Generated by Django 2.2.8 on 2021-08-08 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0004_roleplayingsystem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayingsystem',
            name='player_count',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='roleplayingsystem',
            name='rate_complexity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='roleplayingsystem',
            name='rate_lore',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
