# Generated by Django 2.2.15 on 2021-08-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0006_roleplayingsystem_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayingitem',
            name='external_file_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='roleplayingsystem',
            name='rate_complexity',
            field=models.IntegerField(blank=True, choices=[(1, 'No rules'), (2, 'Rules-light'), (3, 'Average'), (4, 'Rule-heavy'), (5, 'Robust')], null=True),
        ),
    ]
