# Generated by Django 2.2.15 on 2021-08-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0008_auto_20210809_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleplayingitem',
            old_name='digital_version',
            new_name='local_file',
        ),
        migrations.RenameField(
            model_name='roleplayingitem',
            old_name='digital_version_file_name',
            new_name='local_file_name',
        ),
    ]
