# Generated by Django 2.2.15 on 2021-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0009_auto_20210809_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingitem',
            name='local_file_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Filename (without extension)'),
        ),
    ]
