# Generated by Django 2.2.15 on 2021-08-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleplaying', '0010_auto_20210809_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleplayingitem',
            old_name='external_file_location',
            new_name='external_file_url',
        ),
    ]
