# Generated by Django 2.2.25 on 2022-09-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name displayed in Squire', max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('path', models.URLField(blank=True, default=None, help_text='The path to the folder (including the folder itself)')),
            ],
        ),
        migrations.CreateModel(
            name='NCFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name displayed in Squire', max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('file_name', models.CharField(blank=True, default=None, help_text='The file name', max_length=64)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextcloud_integration.NCFolder')),
            ],
        ),
    ]
