# Generated by Django 3.2.16 on 2023-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('nextcloud_integration', '0001_initial'), ('nextcloud_integration', '0002_auto_20220925_1758'), ('nextcloud_integration', '0003_ncfolder_slug'), ('nextcloud_integration', '0004_auto_20221001_1612'), ('nextcloud_integration', '0005_auto_20221012_1618'), ('nextcloud_integration', '0006_auto_20221016_1845'), ('nextcloud_integration', '0007_auto_20221107_2228'), ('nextcloud_integration', '0008_auto_20230108_1558'), ('nextcloud_integration', '0009_auto_20230108_1559'), ('nextcloud_integration', '0010_auto_20230108_1642')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquireNextCloudFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name displayed in Squire', max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('path', models.CharField(blank=True, default=None, help_text='The path to the folder (including the folder itself)', max_length=64)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('on_overview_page', models.BooleanField(default=True, help_text='Whether this folder is displayed on the association download page')),
                ('requires_membership', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SquireNextCloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name displayed in Squire', max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('file_name', models.CharField(blank=True, default=None, help_text='The file name', max_length=64)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nextcloud_integration.squirenextcloudfolder')),
                ('slug', models.SlugField(blank=True)),
                ('connection', models.CharField(choices=[('NcS', 'Synched through file on Nextcloud'), ('SqU', 'Uploaded through Squire')], default='NcS', max_length=3)),
                ('is_missing', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view', 'sync'),
            },
        ),
    ]
