# Generated by Django 3.2.16 on 2023-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0001_squashed_0010_auto_20230108_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirenextcloudfile',
            name='connection',
            field=models.CharField(choices=[('NcS', 'Synched through file on Nextcloud'), ('SqU', 'Uploaded through Squire')], max_length=3),
        ),
    ]
