# Generated by Django 2.2.25 on 2022-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncfolder',
            name='path',
            field=models.CharField(blank=True, default=None, help_text='The path to the folder (including the folder itself)', max_length=64),
        ),
    ]
