# Generated by Django 2.2.25 on 2022-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0002_auto_20220925_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncfolder',
            name='slug',
            field=models.SlugField(default='hey'),
            preserve_default=False,
        ),
    ]
