# Generated by Django 2.2.25 on 2022-10-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0003_ncfolder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncfile',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ncfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nextcloud_integration.NCFolder'),
        ),
    ]
