# Generated by Django 2.2.25 on 2022-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0004_auto_20221001_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncfile',
            name='connection',
            field=models.CharField(choices=[('NcS', 'Synched through file on Nextcloud'), ('SqU', 'Uploaded through Squire')], default='NcS', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncfile',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ncfolder',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ncfile',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
