# Generated by Django 2.2.25 on 2022-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0005_auto_20221012_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncfolder',
            name='on_overview_page',
            field=models.BooleanField(default=True, help_text='Whether this folder is displayed on theassociation download page'),
        ),
        migrations.AddField(
            model_name='ncfolder',
            name='requires_membership',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ncfile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
