# Generated by Django 2.2.25 on 2022-11-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextcloud_integration', '0006_auto_20221016_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncfile',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'synch')},
        ),
    ]
