# Generated by Django 2.2.15 on 2021-08-12 22:24

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardgames', '0001_initial'),
        ('inventory', '0004_move_boardgame_part_1'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BoardGame',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=128)),
                        ('description', models.TextField(blank=True, max_length=512, null=True)),
                        ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_item_image_upload_path)),
                        ('bgg_id', models.IntegerField(blank=True, null=True)),
                        ('player_min', models.PositiveIntegerField(blank=True, null=True)),
                        ('player_max', models.PositiveIntegerField(blank=True, null=True)),
                        ('play_duration', models.CharField(blank=True, choices=[('XS', '<15 min.'), ('S', '< 1 hour'), ('N', '1-2 hours'), ('L', '3-4 hours'), ('XL', '4+ hours')], max_length=2, null=True)),
                    ],
                    options={
                        'ordering': ('name',),
                        'abstract': False,
                        'default_permissions': ('add', 'change', 'delete', 'view', 'add_group_ownership_for', 'add_member_ownership_for', 'maintain_ownerships_for'),
                    },
                ),
            ],
        ),
    ]
