# Generated by Django 2.2.24 on 2021-11-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_move_boardgame_part_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'boardgame'},
        ),
    ]
